export const STRINGS = {
  app: { name: 'GoBookIt' },
  auth: {
    loginTitle: 'Login',
    registerTitle: 'Register',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    show: 'Show',
    hide: 'Hide',
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    signIn: 'Sign In',
    signUp: 'Sign Up',
    loginSuccess: 'Signed in successfully',
    registerSuccess: 'You can now log in!',
    passwordMismatch: 'Passwords do not match',
    loginToBook: 'You must log in first to book a room.',
  },
  bookings: {
    myBookings: 'My Bookings',
    subtitle: 'View and manage all your room bookings',
    noneTitle: 'No bookings yet',
    noneMessage: "You don't have any active bookings. Book a room to get started.",
  },
  rooms: {
    availableRooms: 'Available Rooms',
    availableSubtitle: 'Find and book the meeting space that fits your needs',
    myRooms: 'My Rooms',
    myRoomsSubtitle: 'Manage the rooms you have listed for booking',
    noRoomsOwnerTitle: 'No rooms yet',
    noRoomsOwnerMessage: 'You have not added any rooms.',
    addRoom: 'Add a Room',
    addRoomSubtitle: 'Fill in the details to create a new room',
    viewDetails: 'View Details',
    bookThisRoom: 'Book this Room',
    bookRoom: 'Book Room',
    estimatedCost: 'Estimated Cost',
    startingFrom: 'Starting from',
  },
};
export type StringKeys = typeof STRINGS;
