name: CI & Deploy (Vercel)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint -- --max-warnings=0

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Build
        run: npm run build

      - name: Deploy to Vercel (Preview for PR / Production for main)
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          prod: ${{ github.ref == 'refs/heads/main' }}
        env:
          # Server-only secret
          APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
          # Public env (exposed at build)
          NEXT_PUBLIC_APPWRITE_ENDPOINT: ${{ secrets.NEXT_PUBLIC_APPWRITE_ENDPOINT }}
          NEXT_PUBLIC_APPWRITE_PROJECT: ${{ secrets.NEXT_PUBLIC_APPWRITE_PROJECT }}
          NEXT_PUBLIC_APPWRITE_DATABASE: ${{ secrets.NEXT_PUBLIC_APPWRITE_DATABASE }}
          NEXT_PUBLIC_APPWRITE_COLLECTION_BOOKINGS: ${{ secrets.NEXT_PUBLIC_APPWRITE_COLLECTION_BOOKINGS }}
          NEXT_PUBLIC_APPWRITE_COLLECTION_ROOMS: ${{ secrets.NEXT_PUBLIC_APPWRITE_COLLECTION_ROOMS }}
          NEXT_PUBLIC_APPWRITE_STORAGE_BUCKET_ROOMS: ${{ secrets.NEXT_PUBLIC_APPWRITE_STORAGE_BUCKET_ROOMS }}
          NEXT_PUBLIC_APPWRITE_OAUTH_SUCCESS_URL: ${{ secrets.NEXT_PUBLIC_APPWRITE_OAUTH_SUCCESS_URL }}
          NEXT_PUBLIC_APPWRITE_OAUTH_FAILURE_URL: ${{ secrets.NEXT_PUBLIC_APPWRITE_OAUTH_FAILURE_URL }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_BYPASS_IMAGE_OPT: ${{ secrets.NEXT_PUBLIC_BYPASS_IMAGE_OPT }}
